### ISSUE TITLE
Streaming data to the pager

### ISSUE THREAD

**Issue by AndrewRadev** [piotrmurach/tty-pager#13]
### Describe the problem

This is a feature request rather than an issue. My problem is that (to my knowledge), I can't feed data to the pager as it's running. From what I see and what I've tried, running `pager.page(text)` works fine, but it assumes the text is prepared once and is then printed to the screen.

My use case is that I'm generating data to print continuously, possibly for a while. The specific script I'm writing is [here](https://github.com/AndrewRadev/scripts/blob/1a8789c54b036bdae8eada60b3721aeb8cec84f9/bin/git-todo). It's a filter of `git log`, so it could potentially take a long time to accumulate all commits. That's why I do some accumulation and print every log as it's ready. I don't see a way to do this with tty-pager.

What is currently working for me is the [pager](https://github.com/sferik/pager) gem, which is kind of old, but works wonderfully. It is, however, pretty invasive, reopening stdout, and I'd like to be able to use tty-pager for future needs, since I feel it'd be more easily tested, for instance.

I fully understand that this might be a rare edge case or that it might be difficult to achieve this with the current architecture (I don't know much about how this works). I don't have a pressing need for this functionality, I just think it'd be nice to have. 

### Steps to reproduce the problem

An example of what I'd like to be able to do might look like this:

``` ruby
pager.puts("Some content...")
pager.puts("Some more content")
```

### Describe your environment

* OS version: Arch linux
* Ruby version: 2.6.5
* TTY::Pager version: 0.12.1

**Comment by piotrmurach** [comment]
Hi Andrew,

That's correct as it currently is the pager expects text as an input. However, I like your idea a lot! I think this would be a great change and would make this gem far more useful. When I created it, I had a use case and it served it well. Since then I haven't been using this gem much.

I like your suggestion for the `puts` call. Equally, I was thinking that the `pager` could take a generic IO stream interface, that would support streams, files, subprocess etc. The `IOStream` would take the file descriptor to the stream and expose `each` method internally. This method would continue reading chunks of input (let's say 512) and yield them to the pager instance when a new line is found. In other words, it should be possible to do:

```
pager = TTY::Pager.new(io)
pager.page
```

Then paging would stop printing when stream closes or manual `pager.stop` is called.

Anyhow, do you have time to submit PR?

**Comment by AndrewRadev** [comment]
I'd need to both understand how the logic works in terms of process-juggling, and also understand the codebase, so it would take some time. I don't think I can get around to it during the week, but I'll probably explore over the weekend.

**Comment by piotrmurach** [comment]
There are essentially two pagers. This gem aims to work on any system including Windows. It uses by default a `SystemPager` that calls a process pipe to feed the content. But if `less` or other paging tools are not supported, it falls back on `BasicPager` that manually wraps content and prints it out to standard out. It already works on line by line basis so it should be possible to make it work via the `puts`  calls or IO streaming that would feed it lines as well.

I'm here to answer any queries and provide feedback. I really would appreciate help and having this feature would make this pager even better.
