### ISSUE TITLE
Change class-level page to automatically page files

### ISSUE THREAD

**Issue by piotrmurach** [piotrmurach/tty-pager#21]
The `TTY::Pager.page` could also be made to work out of the box with paths:

```ruby
TTY::Pager.page(path: "/path/to/filename.txt", command: "less -R")
```
or `IO` objects:

```ruby
TTY::Pager.page(io: File.open("filename.txt", "r"), command: "less -R")
```
This could potentially remove a bit of boilerplate code. The return value would be bool status.

@AndrewRadev Any thoughts?

**Comment by AndrewRadev** [comment]
It would make sense, yes. The specific API to use is not an easy question.

Using an IO object would be more flexible, since it might be a file, or a socket, or any other stream. But there's the question of "who closes it?" Having both in the same function also raises the question "what if somebody calls it with both?" It could error out, I guess.

Personally, I'd prefer to be as explicit as possible and provide `page`, `page_io`, and `page_file`. At least the `page`/`page_file` combination is similar to JSON and YAML libraries. `page(text, **options)` is simplest, but implies you have everything in a single file, `page_io(io, ...)` could be used for sockets and pipes, and `page_file("/some/path", ...)` would be easier with files, so you don't have to open and close them manually.

**Comment by piotrmurach** [comment]
I can totally see where you're coming from with the `page`, `page_io` etc. This is definietly a reasonable approach. However, in `tty` gems I try to minimize the API surface as much as possible and let the individual methods pull their weight. I do prefer method overloading kind of behaviour. For example, the [tty-editor](https://github.com/piotrmurach/tty-editor) and other gems take this approach. Because of this, I do lean towards the single `page` method entry.

At least for this release, I wanted to use `IO.foreach` to enumerate a file content(I doesn't slurp up the file and is memory efficient). Not too worried about other streams for now - we can state in the docs that paging only handles strings and files. Practically, this would mean a minimal extension to `TTY::Pager::Abstract#page`:

```ruby
def self.page(text = nil, path: nil, **options)
  instance = new(**options)

  if block_given?
    block.call(intance)
  elsif path
    IO.foreach(path) do |line|
      instance.write line
    end
  else
    instance.page(text)
  end
  # ... 
end
```

**Comment by piotrmurach** [comment]
@AndrewRadev I took a stab a this. What do you think?

**Comment by AndrewRadev** [comment]
@piotrmurach I left some comments. It generally looks good, my main recommendation would be to handle mixed arguments in a clearer way for the user.

**Comment by piotrmurach** [comment]
@AndrewRadev Appreciate the comments. Changed to raise errors when inputs are mixed and updated parameter list with docs.

**Comment by piotrmurach** [comment]
@AndrewRadev Released and updated `tty-screen` which has many improvements and will be part of this release. I'm also almost done refactoring `BasicPager` to tell a better story. Hopefully will be able to release soon.
